### ISSUE TITLE
Admin record causes crash

### ISSUE THREAD

**Issue by christroutner** [christroutner/koa-api-boilerplate#56]
There is a strange startup behavior that I've observed multiple times and other users have reported. From @vinarmani:

> I was runnning into a weird issue where the api server would error out on init if there already was an admin record. If I deleted the admin user record, it would load up fine. Have you experienced that?

My typical solution is to drop the Mongo database. But this step is not obvious to other users.

The scope of this Issue is to figure out how to reliably reproduce this issue and the investigate how to automatically drop the database or take some other automated mitigation step.

**Comment by vinarmani** [comment]
Quick patch is just to hard code an _id for the admin user (as email is being hard coded) in [admin.js](https://github.com/christroutner/koa-api-boilerplate/blob/master/src/lib/admin.js#L41)

```
const options = {
      method: 'POST',
      uri: `${LOCALHOST}/users`,
      resolveWithFullResponse: true,
      json: true,
      body: {
        user: {
          email: 'system@system.com',
          password: context.password,
          _id: '5e3314136772a049f40a45a0'
        }
      }
    }
    let result = await rp(options)
```

**Comment by christroutner** [comment]
I was able to replicate the failure mode. Here is the typical output:

```
Running server in environment: dev
Server started on 5001
  <-- POST /users
  --> POST /users 422 116ms 109b
Admin .json file not found!
Error in admin.js/loginAdmin().
Error in admin.js/deleteExistingSystemUser()
Error in admin.js/createSystemUser() while trying generate new system user.
(node:19140) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/trout/work/personal/koa-api-boilerplate/src/lib/../../config/system-user-dev.json'
(node:19140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Here are the contents of my `config/env/development.js` file:

```
module.exports = {
  session: 'secret-boilerplate-token',
  token: 'secret-jwt-token',
  database: 'mongodb://localhost:27017/koa-server-dev',
  env: 'dev'
}
```

I think this was caused by the database existing, but the `admin.json` file not existing.

**Comment by christroutner** [comment]
## Steps to reproduce:
- If you have never installed this repo on the current machine, clone this repository and follow the setup instructions. Install MongoDB with the install script in the directions. Ensure you can run `npm start`. This ensures that a `koa-server-dev` database exists inside Mongo.
- Delete the repository on your local machine.
- Clone the repository and set it up again. Install dependencies. Run `npm start`

You should receive the same error messages I have posted above.

This is caused by the `koa-server-dev` database existing with an admin user, but no `config/system-user-dev.json` file does not exist. It tries to delete the existing admin user to recreate it, but does not have the proper permissions.

**Comment by christroutner** [comment]
## Solution:

The [deleteExistingSystemUser()](https://github.com/christroutner/koa-api-boilerplate/blob/master/src/lib/admin.js#L91) function uses the normal `/user` API endpoint to try and delete the admin user. This function should be refactored in order to interact directly with the database.

The code in [utils/users/delete-all-test-users.js](https://github.com/christroutner/koa-api-boilerplate/blob/master/util/users/delete-all-test-users.js) can be modified for use here. This app is an example of interacting directly with the database. This app uses a query to retrieve all users. This query would need to be modified to retrieve just the admin/system user.

**Comment by christroutner** [comment]
Handing this fix off to @danielhumgon

**Comment by danielhumgon** [comment]
Hi @christroutner ! worked to solve this issue in this PR --> https://github.com/christroutner/koa-api-boilerplate/pull/58 it should be fixed now

**Comment by christroutner** [comment]
Great work! Problem solved.
